language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
# Build only commits on master and release tags for the "Build pushed branches" feature.
# This prevents building twice on PRs originating from our repo ("Build pushed pull requests)".
# See:
#   - https://github.com/travis-ci/travis-ci/issues/1147
#   - https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
branches:
  only:
    - master
    - develop
    - /v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/

services: docker
# Global env variables
env:
  global:
    - XS2a_ADAPTER_UI_IMAGE="xs2a-adapter-ui"
    - OPENSHIFT_REGISTRY="openshift-registry.adorsys.de"
    - OPENSHIFT_NAMESPACE="xs2a-adapter-dev"

install:
  - mvn --version

stages:
  - build
  - test-ui
  - test-it
jobs:
  include:
    - stage: build
      script:
        - echo "Build xs2a-adapter-ui"
        - mvn -ntp clean install -DskipITs -DskipTests -Djacoco.skip=false
    - stage: test-ui
      script:
        - echo "Run Unit tests xs2a-adapter-ui"
        - mvn -ntp -DskipITs  test
    - stage: test-it
      script:
        - echo "Run Integration tests xs2a-adapter-ui"
        - mvn -ntp failsafe:integration-test failsafe:verify